export type WordType = {
  word: string;
  definition: string;
};
export const wordsInit: WordType[] = [
  {
    word: "pollute",
    definition: "làm ô nhiễm môi trường\n=to make the environment dirty",
  },
  {
    word: "extinguisher",
    definition: "bình chữa cháy\n=Device used to put out fires",
  },
  {
    word: "someday",
    definition: "một thời điểm nào đó\n=At some unspecified time in the future",
  },
  {
    word: "rainfall",
    definition:
      "lượng mưa\n=Water that falls from the clouds in the sky, in little drops",
  },
  {
    word: "penalize",
    definition: "phạt\n=to punish someone",
  },
  {
    word: "prescribe",
    definition:
      "ra lệnh, quy định, bắt phải\n=to formally tell someone what to do",
  },
  {
    word: "flaw",
    definition:
      "khuyết điểm, lỗi hỏng\n=something that is faulty in otherwise perfect person/thing",
  },
  {
    word: "rug",
    definition: "thảm trải sàn\n=a small loose floor covering",
  },
];

export const entertainmentVocabulary: WordType[] = [
  { word: "anthology", definition: "tuyển tập" },
  { word: "applaud", definition: "vỗ tay" },
  { word: "article", definition: "bài báo" },
  { word: "artistic", definition: "thuộc về nghệ thuật" },
  { word: "audience", definition: "khán giả" },
  { word: "auditorium", definition: "hội trường" },
  { word: "biographical", definition: "tiểu sử" },
  { word: "broadcast", definition: "phát sóng" },
  { word: "broadsheet", definition: "báo khổ lớn" },
  { word: "celebrity", definition: "người nổi tiếng" },
  { word: "censorship", definition: "sự kiểm duyệt" },
  { word: "collaboration", definition: "sự cộng tác" },
  { word: "comedy", definition: "hài kịch" },
  { word: "compose", definition: "sáng tác" },
  { word: "critic", definition: "nhà phê bình" },
  { word: "delight", definition: "thích thú, vui mừng" },
  { word: "documentary", definition: "phim tài liệu" },
  { word: "evaluate", definition: "đánh giá" },
  { word: "genre", definition: "thể loại" },
  { word: "headline", definition: "tiêu đề" },
  { word: "humorous", definition: "hài hước" },
  { word: "inspiration", definition: "sự cảm hứng" },
  { word: "musical instrument", definition: "nhạc cụ" },
  {
    word: "journalist",
    definition: "nhà báo = a person who writes for newspapers, magazines",
  },
  { word: "nominate", definition: "đề cử" },
  { word: "orchestra", definition: "dàn nhạc" },
  { word: "paparazzi", definition: "thợ săn ảnh" },
  { word: "performance", definition: "buổi biểu diễn" },
  { word: "portrait", definition: "chân dung" },
  { word: "premiere", definition: "ra mắt phim/truyện" },
  { word: "press (noun)", definition: "truyền thông, báo chí" },
  { word: "publisher", definition: "nhà xuất bản" },
  { word: "readership", definition: "độc giả" },
  { word: "recital", definition: "độc tấu (biểu diễn 1 mình)" },
  { word: "recreational", definition: "giải trí" },
  { word: "rehearse", definition: "diễn tập" },
  { word: "release", definition: "phát hành" },
  { word: "repertoire", definition: "tiết mục" },
  { word: "skillfully", definition: "khéo léo" },
  { word: "soundtrack", definition: "nhạc phim" },
  { word: "subcription", definition: "đăng ký" },
  { word: "tabloid", definition: "báo lá cải" },
  { word: "theatergoer", definition: "khán giả xem kịch" },
  { word: "theme", definition: "chủ đề" },
  { word: "viewership", definition: "lượng người xem" },
];

export const technologyVocabulary: WordType[] = [
  { word: "appliance", definition: "thiết bị" },
  { word: "automatic", definition: "tự động" },
  { word: "breakthrough", definition: "sự đột phá" },
  { word: "browse", definition: "đọc lướt, tra cứu" },
  { word: "database", definition: "cơ sở dữ liệu" },
  { word: "capacity", definition: "bộ nhớ, dung lượng, sức chứa" },
  { word: "commerce", definition: "thương mại" },
  { word: "compatible", definition: "tương thích" },
  { word: "complicated", definition: "phức tạp" },
  { word: "connection", definition: "sự kết nối" },
  { word: "control", definition: "kiểm soát, điều khiển" },
  { word: "cutting-edge", definition: "hiện đại" },
  { word: "duplicate", definition: "nhân bản, tạo bản sao" },
  { word: "function", definition: "chức năng" },
  { word: "grant", definition: "cấp, ban cho" },
  { word: "gadget", definition: "đồ dùng (thiết bị điện tử nhỏ)" },
  { word: "impact", definition: "tầm ảnh hưởng" },
  { word: "innovative", definition: "đổi mới" },
  { word: "install", definition: "lắp đặt" },
  { word: "intertact", definition: "tương tác" },
  { word: "interruption", definition: "gián đoạn" },
  { word: "machinery", definition: "máy móc" },
  { word: "manufacturer", definition: "nhà sản xuất" },
  { word: "maintenance", definition: "bảo dưỡng, bảo trì" },
  { word: "modify", definition: "chỉnh sửa" },
  { word: "outdated", definition: "lỗi thời" },
  { word: "change", definition: "thay đổi" },
  { word: "vary", definition: "biến đổi (tùy theo tình huống)" },
  { word: "printer", definition: "máy in" },
  { word: "register", definition: "đăng ký" },
  { word: "screen", definition: "màn hình" },
  { word: "software", definition: "phần mềm máy tính" },
  { word: "system", definition: "hệ thống" },
  { word: "upgrade", definition: "nâng cấp" },
  { word: "virtual", definition: "ảo" },
  { word: "wireless", definition: "không dây" },
  { word: "warrant", definition: "bảo đảm" },
];

export const dinningoutVocabulary: WordType[] = [
  {
    word: "pollute",
    definition: "làm ô nhiễm môi trường\n=to make the environment dirty",
  },
  {
    word: "extinguisher",
    definition: "bình chữa cháy\n=Device used to put out fires",
  },
  {
    word: "someday",
    definition: "một thời điểm nào đó\n=At some unspecified time in the future",
  },
  {
    word: "rainfall",
    definition:
      "lượng mưa\n=Water that falls from the clouds in the sky, in little drops",
  },
  { word: "penalize", definition: "phạt\n=to punish someone" },
  {
    word: "prescribe",
    definition:
      "ra lệnh, quy định, bắt phải\n=to formally tell someone what to do",
  },
  {
    word: "flaw",
    definition:
      "khuyết điểm, lỗi hỏng\n=something that is faulty in otherwise perfect person/thing",
  },
  { word: "rug", definition: "thảm trải sàn\n=a small loose floor covering" },
  { word: "afford", definition: "đủ tiền để trả cái gì đó" },
  { word: "affordable", definition: "giá cả phải chăng" },
  { word: "appetizer", definition: "món khai vị" },
  { word: "bacon", definition: "thịt xông khói" },
  { word: "banquet", definition: "yến tiệc" },
  { word: "bartender", definition: "người pha chế" },
  { word: "bistro", definition: "nhà hàng bình dân" },
  { word: "budget", definition: "rẻ /ngân sách" },
  { word: "busboy", definition: "nhân viên dọn bàn" },
  { word: "cafeteria / canteen", definition: "nhà ăn" },
  { word: "centrepiece", definition: "phần quan trọng nhất" },
  { word: "chef", definition: "bếp trưởng" },
  { word: "classy", definition: "sang trọng" },
  { word: "combo", definition: "thực đơn kết hợp" },
  { word: "compliment", definition: "lời khen" },
  { word: "complimentary", definition: "miễn phí" },
  { word: "spice", definition: "gia vị (có nguồn gốc thực vật)" },
  { word: "condiment", definition: "gia vị" },
  { word: "handy", definition: "thuận tiện (cho các đồ vật)" },
  { word: "convenient", definition: "thuận tiện (cho tất cả ngữ cảnh)" },
  { word: "decoration", definition: "trang trí" },
  { word: "dessert", definition: "món tráng miệng" },
  { word: "etiquette", definition: "quy tắc ứng xử" },
  { word: "flavour", definition: "hương vị" },
  { word: "flavourful", definition: "thơm ngon" },
  { word: "flour", definition: "bột mỳ" },
  { word: "grill", definition: "nướng" },
  { word: "highchair", definition: "ghế trẻ em" },
  { word: "hospitable", definition: "sự thân thiện" },
  { word: "ingredient", definition: "thành phần" },
  { word: "leftover", definition: "thức ăn thừa" },
  { word: "mouth-watering", definition: "ngon lành/ vừa miệng" },
  {
    word: "tissue",
    definition: "khăn giấy (mỏng hơn napkin) thường dùng để xì mũi",
  },
  { word: "napkin", definition: "khăn giấy, giấy ăn" },
  { word: "nutrient", definition: "chất dinh dưỡng" },
  { word: "nutritious", definition: "bổ dưỡng" },
  { word: "organic", definition: "thực phẩm hữu cơ" },
  {
    word: "pastry",
    definition:
      "bánh ngọt (từ sử dụng chung để chỉ các sản phẩm làm từ trứng, bột, sữa. Cake chỉ là 1 loại trong Pastry)",
  },
  { word: "patio", definition: "khu ngồi ngoài trời / hiên nhà" },
  { word: "patron", definition: "khách quen" },
  { word: "recipe", definition: "công thức" },
  { word: "reservation", definition: "sự đặt trước" },
  { word: "starving", definition: "đói cồn cào, rất đói" },
  { word: "sommelier", definition: "người thử rượu" },
  { word: "spacious", definition: "rộng rãi" },
  { word: "season", definition: "cho gia vị" },
  { word: "large", definition: "to lớn (về số lượng, kích cỡ)" },
  { word: "huge", definition: "tương tự như large nhưng có mức độ lớn hơn" },
  { word: "speciality", definition: "đặc sản" },
  { word: "tip", definition: "tiền thưởng (từ khách hàng cho người phục vụ)" },
  { word: "bonus", definition: "tiền thưởng thêm từ công ty" },
  { word: "allowance", definition: "tiền phụ cấp" },
  { word: "commission", definition: "tiền hoa hồng" },
  {
    word: "vegetarian",
    definition:
      "người ăn chay (nhưng vẫn sử dụng các thực phẩm có nguồn gốc từ động vật như trứng, sữa)",
  },
  { word: "vegan", definition: "người ăn chay thuần" },
  { word: "waiter", definition: "phục vụ nam" },
  { word: "waitress", definition: "phục vụ nữ" },
  { word: "reserve", definition: "đặt trước (thanh toán sau khi sử dụng)" },
  {
    word: "book",
    definition: "đặt trước (nhưng đã thanh toán trước khi sử dụng)",
  },
];
